namespace Project1.Welcome;

public static class WelcomeToTheGame
{
    public static void Start()
    {
        Console.Clear();
        Console.ForegroundColor = ConsoleColor.Green;
        Console.WriteLine("      _,.");
        Console.WriteLine("    ,` -.)");
        Console.WriteLine("   ( _/-\\\\-._                             Warrior's Quest");
        Console.WriteLine("  /,|`--._,-^|            ,         The search for a passing grade");
        Console.WriteLine("  \\_| |`-._/||          ,'|");
        Console.WriteLine("    |  `-, / |         /  /");
        Console.WriteLine("    |     || |        /  /                 L: Login");
        Console.WriteLine("     `r-._||/   __   /  /                  C: Create New Character");
        Console.WriteLine(" __,-<_     )`-/  `./  /                   X: Exit");
        Console.WriteLine("'  \\   `---'   \\   /  /");
        Console.WriteLine("    |           |./  /");
        Console.WriteLine("    /           //  /");
        Console.WriteLine("\\_/' \\         |/  /");
        Console.WriteLine(" |    |   _,^-'/  /");
        Console.WriteLine(" |    , ``  (\\/  /_");
        Console.WriteLine("  \\,.->._    \\X-=/^");
        Console.WriteLine("  (  /   `-._//^`");
        Console.WriteLine("   `Y-.____(__}");
        Console.WriteLine("    |     {__)");
        Console.WriteLine("          ()");
        Console.ResetColor();
        Console.ReadKey();
        
        Console.Clear();
        //Console.ForegroundColor = ConsoleColor.DarkYellow;
        Console.WriteLine("     _   _");
        Console.WriteLine("    (q\\_/p)");
        Console.WriteLine(".-.  |. .|");
        Console.WriteLine("   \\ =\\,/=");
        Console.WriteLine("    )/ _ \\ ");
        Console.WriteLine("   (/\\):(/\\");
        Console.WriteLine("    \\_   _/ ");
        Console.WriteLine("    `\"\"^\"\"` ");
        Console.ReadKey();

        Console.Clear();
        Console.WriteLine("                         ____    .-.");
        Console.WriteLine("                     .-\"`    `\",( __\\_");
        Console.WriteLine("      .-==:;-._    .'         .-.     `'.");
        Console.WriteLine("    .'      `\"-:'-/          (  \\} -=a  .)");
        Console.WriteLine("   /            \\/       \\,== `-  __..-'`");
        Console.WriteLine("'-'              |       |   |  .'\\ `;");
        Console.WriteLine("                  \\    _/---'\\ (   `\"`");
        Console.WriteLine("                 /.`._ )      \\ `;");
        Console.WriteLine("                 \\`-/.'        `\"`");
        Console.WriteLine("                  `\"\\`-.");
        Console.WriteLine("                     `\"`");
        Console.ReadKey();

        Console.Clear();
        Console.WriteLine("          __       __     _");
        Console.WriteLine("         /-.\\     /  \\   //");
        Console.WriteLine("         \\  \\|_,_/|  /  ((");
        Console.WriteLine("          `\\ `    `\\\"    \\\\");
        Console.WriteLine("          /  _   _  \\     ))");
        Console.WriteLine("         |  (0\\ /0)  |   //");
        Console.WriteLine("         \\           /  //");
        Console.WriteLine("         /`.== 0 ==.`\\ ((");
        Console.WriteLine("        /   `~~W~~`   \\ \\");
        Console.WriteLine("       |   ,       ,   | ))");
        Console.WriteLine("       \\   \\       /   ///");
        Console.WriteLine("       /`vvvv     vvvv`\\/");
        Console.WriteLine("      |                 |");
        Console.WriteLine("      |   |         |   |");
        Console.WriteLine("     /    (         )    \\");
        Console.WriteLine("    (v(v(v)`=.....=`(v)v)v)");
        Console.ReadKey();

        Console.Clear();
        Console.WriteLine("  / _ \\");
        Console.WriteLine("\\_\\(_)/_/");
        Console.WriteLine(" _//\"\\\\_ ");
        Console.WriteLine("  /   \\");
        Console.ReadKey();

        Console.Clear();
        Console.WriteLine("           ____                      ,");
        Console.WriteLine("          /---.'.__             ____//");
        Console.WriteLine("               '--.\\           /.---'");
        Console.WriteLine("          _______  \\\\         //");
        Console.WriteLine("        /.------.\\  \\|      .'/  ______");
        Console.WriteLine("       //  ___  \\ \\ ||/|\\  //  _/_----.\\__");
        Console.WriteLine("      |/  /.-.\\  \\ \\:|< >|// _/.'..\\   '--'");
        Console.WriteLine("         //   \\'. | \\'.|.'/ /_/ /  \\\\");
        Console.WriteLine("        //     \\ \\_\\/\" ' ~\\-'.-'    \\\\");
        Console.WriteLine("       //       '-._| :H: |'-.__     \\\\");
        Console.WriteLine("      //           (/'==='\\)'-._\\     ||");
        Console.WriteLine("      ||                        \\\\    \\|");
        Console.WriteLine("      ||                         \\\\    '");
        Console.WriteLine("      |/                          \\\\");
        Console.WriteLine("                                   ||");
        Console.WriteLine("                                   ||");
        Console.WriteLine("                                   \\\\");
        Console.WriteLine("                                    '");
        Console.ReadKey();

        Console.Clear();
        Console.ForegroundColor = ConsoleColor.DarkRed;
        Console.WriteLine("        _____");
        Console.WriteLine("    .-,;='';_),-.");
        Console.WriteLine("     \\_\\(),()/_/");
        Console.WriteLine("       (,___,)");
        Console.WriteLine("      ,-/`~`\\-,___");
        Console.WriteLine("     / /).:.('--|_)");
        Console.WriteLine("    {_[ (_,_)  _|_|_");
        Console.WriteLine("        | Y | (_____)");
        Console.WriteLine("       /  |  \\");
        Console.WriteLine("       \"\"\" \"\"\"");
        Console.ReadKey();

        Console.Clear();
        Console.WriteLine("        _____");
        Console.WriteLine("    .-,;='';_),-. ");
        Console.WriteLine("     \\_\\(),()/_/|\\");
        Console.WriteLine("       (,___,)  | \\");
        Console.WriteLine("      ,-/`~`\\-,_|_|)");
        Console.WriteLine("     / /).:.('--._=) ");
        Console.WriteLine("    {_[ (_,_)   | |)");
        Console.WriteLine("        | Y |   | /");
        Console.WriteLine("       /  |  \\  |/");
        Console.WriteLine("       \"\"\" \"\"\"");
        Console.ReadKey();

        Console.Clear();
        Console.WriteLine("        _____   /\\");
        Console.WriteLine("    .-,;='';_),-\\/ ");
        Console.WriteLine("     \\_\\(),()/_/||");
        Console.WriteLine("       (,___,)  ||");
        Console.WriteLine("    ___-/`~`\\-,_||");
        Console.WriteLine("   /   \\).:.('--._) ");
        Console.WriteLine("  | []  |_,_)   ||");
        Console.WriteLine("   \\___/| Y |   || ");
        Console.WriteLine("       /  |  \\  ||");
        Console.WriteLine("       \"\"\" \"\"\"");
        Console.ReadKey(); 

        Console.Clear();  
        Console.WriteLine("                   _");
        Console.WriteLine("      __ __       //_/\\");
        Console.WriteLine("   .-',,^,,'.    //_   \\");
        Console.WriteLine("  / \\(0)(0)/ \\  //  /  /");
        Console.WriteLine("  )/( ,_\"_,)\\( //_ /  /");
        Console.WriteLine("  `  >-`~(   '//_    /");
        Console.WriteLine("_N\\ |(`\\ |___//  /__/");
        Console.WriteLine("\' |/ \\ \\/_-,))");
        Console.WriteLine(" '.(  \\`\\_<//");
        Console.WriteLine("    \\ _\\| //");
        Console.WriteLine("     | |_\\/_");
        Console.WriteLine("     \\_,_>-'");
        //Console.ResetColor();
        Console.ReadKey();  

        Console.Clear();  
        Console.WriteLine("          /                            )");
        Console.WriteLine("          (                             |\\");
        Console.WriteLine("         /|                              \\\\");
        Console.WriteLine("        //                                \\\\");
        Console.WriteLine("       ///                                 \\|");
        Console.WriteLine("      /( \\                                  )\\");
        Console.WriteLine("      \\\\  \\_                               //)");
        Console.WriteLine("       \\\\  :\\__                           ///");
        Console.WriteLine("        \\\\     )                         // \\");
        Console.WriteLine("         \\\\:  /                         // |/");
        Console.WriteLine("          \\\\ / \\                       //  \\");
        Console.WriteLine("           /)   \\   ___..-'           (|  \\_|");
        Console.WriteLine("          //     /   _.'              \\ \\  \\");
        Console.WriteLine("         /|       \\ \\________          \\ | /");
        Console.WriteLine("        (| _ _  __/          '-.       ) /.'");
        Console.WriteLine("         \\\\ .  '-.__            \\_    / / \\");
        Console.WriteLine("          \\\\_'.     > --._ '.     \\  / / /");
        Console.WriteLine("           \\ \\      \\     \\  \\     .' /.'");
        Console.WriteLine("            \\ \\  '._ /     \\ )    / .' |");
        Console.WriteLine("             \\ \\_     \\_   |    .'_/ __/");
        Console.WriteLine("              \\  \\      \\_ |   / /  _/ \\_");
        Console.WriteLine("               \\  \\       / _.' /  /     \\");
        Console.WriteLine("               \\   |     /.'   / .'       '-,_");
        Console.WriteLine("                \\   \\  .'   _.'_/             \\");
        Console.WriteLine("   /\\    /\\      ) ___(    /_.'           \\    |");
        Console.WriteLine("  | _\\__// \\    (.'      _/               |    |");
        Console.WriteLine("  \\/_  __  /--'`    ,                   __/    /");
        Console.WriteLine("  (_ ) /b)  \\  '.   :            \\___.-'_/ \\__/");
        Console.WriteLine("  /:/:  ,     ) :        (      /_.'__/-'|_ _ /");
        Console.WriteLine(" /:/: __/\\ >  __,_.----.__\\    /        (/(/(/");
        Console.WriteLine("(_(,_/V .'/--'    _/  __/ |   /");
        Console.WriteLine(" VvvV  //`    _.-' _.'     \\   \\");
        Console.WriteLine("   n_n//     (((/->/        |   /");
        Console.WriteLine("   '--'         ~='          \\  |");
        Console.WriteLine("                              | |_,,,");
        Console.WriteLine("                              \\  \\  /");
        Console.WriteLine("                               '.__)");

        Console.ReadKey(); 
    }
}